export const mainRoutes = [
    { path: '/', page: 'Home.jsx' },
    { path: '/home', page: 'Home.jsx' },
    { path: '/more-info', page: 'FAQs/MoreInfo.jsx' },
    { path: '/faqs', page: 'FAQs/FAQs.jsx' },
    { path: '/minimum-stage-age', page: 'FAQs/MinimumStageAge.jsx' },
    { path: '/covid-19', page: 'FAQs/Covid19.jsx' },
    { path: '/vacancies', page: 'Vacancies.jsx' },
    { path: '/admission', page: 'Admission/Admission.jsx' },
    { path: '/admission/admission-process', page: 'Admission/AdmissionProcess.jsx' },
    { path: '/admission/admission-requirements', page: 'Admission/AdmissionRequirements.jsx' },
    { path: '/admission/inside-egypt-requirements', page: 'Admission/InsideEgyptRequirements.jsx' },
    { path: '/admission/outside-egypt-requirements', page: 'Admission/OutsideEgyptRequirements.jsx' },
    { path: '/admission/outside-egypt-requirements-foreigners', page: 'Admission/OutsideEgyptRequirementsForeigners.jsx' },
    { path: '/admission/admission-fees', page: 'Admission/AdmissionFees.jsx' },
    { path: '/academics', page: 'Academics/Academics.jsx', props: (ctx) => ({ isMobileApp: !!ctx.isMobileApp }) },
    { path: '/academics/kindergarten', page: 'Academics/KindergartenAcademics.jsx' },
    { path: '/academics/kindergarten-international', page: 'Academics/KindergartenInternationalAcademics.jsx' },
    { path: '/academics/kindergarten-national', page: 'Academics/KindergartenNationalAcademics.jsx' },
    { path: '/academics/pre-kindergarten', page: 'Academics/PreKindergartenAcademics.jsx' },
    { path: '/academics/british', page: 'Academics/British.jsx' },
    { path: '/academics/national', page: 'Academics/National.jsx' },
    { path: '/academics/american', page: 'Academics/American.jsx' },
    { path: '/academics/partners', page: 'Academics/Partners.jsx' },
    { path: '/academics/facilities', page: 'Academics/Facilities.jsx' },
    { path: '/academics/staff', page: 'Academics/Staff.jsx', chromeExcluded: true },
    { path: '/academics/staff/national-staff', page: 'Academics/Staff/NationalStaff.jsx' },
    { path: '/academics/staff/british-staff', page: 'Academics/Staff/BritishStaff.jsx' },
    { path: '/academics/staff/american-staff', page: 'Academics/Staff/AmericanStaff.jsx' },
    { path: '/academics/staff/kindergarten-staff', page: 'Academics/Staff/KindergartenStaff.jsx' },
    { path: '/students-life', page: 'StudentsLife/StudentsLife.jsx' },
    { path: '/students-life/students-union', page: 'StudentsLife/StudentsUnion.jsx' },
    { path: '/students-life/alumni-students', page: 'StudentsLife/AlumniStudents/AlumniStudents.jsx' },
    { path: '/students-life/alumni-students/login', page: 'StudentsLife/AlumniStudents/AlumniLogin.jsx', prerender: false },
    { path: '/students-life/alumni-students/profile', page: 'StudentsLife/AlumniStudents/AlumniProfile.jsx', prerender: false },
    { path: '/students-life/activities', page: 'StudentsLife/Activities.jsx' },
    { path: '/students-life/library', page: 'StudentsLife/Library/Library.jsx' },
    { path: '/students-life/library/english-fairy-tales', page: 'StudentsLife/Library/EnglishFairyTales.jsx' },
    { path: '/students-life/library/english-drama', page: 'StudentsLife/Library/EnglishDrama.jsx' },
    { path: '/students-life/library/english-levels', page: 'StudentsLife/Library/EnglishLevels.jsx' },
    { path: '/students-life/library/english-general', page: 'StudentsLife/Library/EnglishGeneral.jsx' },
    { path: '/students-life/library/arabic-information', page: 'StudentsLife/Library/ArabicInformation.jsx' },
    { path: '/students-life/library/arabic-general', page: 'StudentsLife/Library/ArabicGeneral.jsx' },
    { path: '/students-life/library/arabic-religion', page: 'StudentsLife/Library/ArabicReligion.jsx' },
    { path: '/students-life/library/arabic-stories', page: 'StudentsLife/Library/ArabicStories.jsx' },
    { path: '/events', page: 'Events/Events.jsx' },
    { path: '/events/national-calendar', page: 'Events/NationalCalendar.jsx' },
    { path: '/events/british-calendar', page: 'Events/BritishCalendar.jsx' },
    { path: '/events/american-calendar', page: 'Events/AmericanCalendar.jsx' },
    { path: '/events/kg-calendars', page: 'Events/KGCalendars.jsx' },
    { path: '/events/american-kg-calendar', page: 'Events/AmericanKGCalendar.jsx' },
    { path: '/events/british-kg-calendar', page: 'Events/BritishKGCalendar.jsx' },
    { path: '/events/national-kg-calendar', page: 'Events/NationalKGCalendar.jsx' },
    { path: '/events/graduation-booking', page: 'Events/GraduationBooking/GraduationBookingLogin.jsx', prerender: false },
    { path: '/events/graduation-booking/dashboard', page: 'Events/GraduationBooking/GraduationBookingDashboard.jsx', prerender: false },
    { path: '/events/graduation-booking/media', page: 'Events/GraduationBooking/GraduationBookingMedia.jsx', prerender: false },
    { path: '/events/graduation-booking/extras', page: 'Events/GraduationBooking/GraduationBookingExtras.jsx', prerender: false },
    { path: '/events/graduation-booking/info', page: 'Events/GraduationBooking/GraduationBookingStatusInfo.jsx', prerender: false },
    { path: '/events/graduation-booking-confirmation', page: 'Events/GraduationBooking/GraduationBookingConfirmation.jsx', prerender: false },
    { path: '/events/open-day-signup', page: 'Events/OpenDaySignup.jsx', prerender: false },
    { path: '/gallery', page: 'Gallery/Gallery.jsx' },
    { path: '/gallery/photos', page: 'Gallery/Photos.jsx' },
    { path: '/gallery/videos', page: 'Gallery/Videos.jsx' },
    { path: '/gallery/360-tour', page: 'Gallery/360Tour.jsx' },
    { path: '*', page: 'NotFound.jsx' },
];

export const adminRoutes = [
    { path: '/', redirect: '/admin-login', section: 'admin' },
    { path: '/admin-login', page: 'Admin/AdminLogin.jsx', section: 'admin', adminEntry: true,
        props: (ctx) => ({ isMobileApp: !!ctx.isMobileApp }) },
    { path: '/admin-dashboard', page: 'Admin/AdminDashboard.jsx', section: 'admin',
        props: (ctx) => ({
            dashboardOptions: ctx.adminLinks,
            adminPermissions: ctx.adminPermissions,
            isLoading: ctx.isAuthLoading,
            loggedInName: ctx.loggedInName,
        }) },
    { path: '/job-applications', page: 'Admin/JobApplications.jsx', section: 'admin' },
    { path: '/graduation-booking-management', page: 'Admin/GraduationBookingManagement.jsx', section: 'admin' },
    { path: '/open-day-signups-management', page: 'Admin/OpenDaySignupsManagement.jsx', section: 'admin' },
    { path: '/borrowing-system-management', page: 'Admin/BorrowingSystemManagement.jsx', section: 'admin' },
    { path: '/info-system-management', page: 'Admin/InfoSystemManagement.jsx', section: 'admin' },
    { path: '/view-job-application-file', page: 'Admin/FileViewer.jsx', section: 'admin',
        props: (ctx) => ({ fetchFileService: ctx.services.serveJobApplicationFile }) },
    { path: '/view-alumni-file', page: 'Admin/FileViewer.jsx', section: 'admin',
        props: (ctx) => ({ fetchFileService: ctx.services.serveAlumniFile }) },
    { path: '/admin-users-management', page: 'Admin/AdminUsersManagement.jsx', section: 'admin',
        props: (ctx) => ({
            loggedInUserId: ctx.loggedInUserId,
            setRefreshCurrentUserData: ctx.setRefreshCurrentUserData,
        }) },
    { path: '/alumni-students-management', page: 'Admin/AlumniStudentsManagement.jsx', section: 'admin' },
    { path: '*', page: 'NotFound.jsx', section: 'admin' },
];

export const corporateRoutes = [
    { path: '/', page: 'CorporateHome.jsx' },
    { path: '/home', page: 'CorporateHome.jsx' },
    { path: '*', page: 'NotFound.jsx' },
];

export const mobileRoutes = [
    ...mainRoutes.filter((r) => r.path !== '*'),
    ...adminRoutes.filter((r) => r.path !== '/' && r.path !== '*'),
    { path: '*', page: 'NotFound.jsx' },
];

function prerenderPathsOf(routes) {
    return routes
        .filter((r) => r.page && r.path !== '*' && r.prerender !== false)
        .map((r) => r.path);
}

export const prerenderTargets = {
    main: {
        distDir: 'dist/static',
        entry: './dist/prerender/entry-prerender-main.js',
        domain: 'https://www.harvestschools.com',
        routes: [...prerenderPathsOf(mainRoutes), '/not-found'],
        sitemapExclude: ['/not-found'],
    },
    corporate: {
        distDir: 'dist/corporate/static',
        entry: './dist/corporate/prerender/entry-prerender-corporate.js',
        domain: 'https://www.alfajralbasem.com',
        routes: [...prerenderPathsOf(corporateRoutes), '/not-found'],
        sitemapExclude: ['/not-found'],
    },
};
