<?php

$ADMIN_USER_MANAGEMENT = "1000";
$JOB_APPLICATION_MANAGEMENT = "0";
$GRADUATION_BOOKING_MANAGEMENT = "1";
$OPEN_DAY_SIGNUP_MANAGEMENT = "2";
$BORROWING_SYSTEM_MANAGEMENT = "3";
$INFO_SYSTEM_MANAGEMENT = "7";
$ALUMNI_STUDENTS_MANAGEMENT = "13";
$STAFF_DIRECTORY_MANAGEMENT = "14";
$ACADEMIC_CALENDARS_MANAGEMENT = "15";
$NATIONAL_CALENDAR_MANAGEMENT = "16";
$BRITISH_CALENDAR_MANAGEMENT = "17";
$AMERICAN_CALENDAR_MANAGEMENT = "18";
$NATIONAL_KG_CALENDAR_MANAGEMENT = "19";
$BRITISH_KG_CALENDAR_MANAGEMENT = "20";
$AMERICAN_KG_CALENDAR_MANAGEMENT = "21";
$LIBRARY_MANAGEMENT = "22";
$GALLERY_MANAGEMENT = "23";
$JACK_OF_ALL_TRADES = "7246262252458111903";