<?php

const PUBLIC_PAGE_INVENTORY = [
    ['id' => 'page.home', 'path' => '/home', 'section' => 'general', 'titleKey' => 'nav.home', 'titleEn' => 'Home', 'keywords' => ['home', 'main', 'الرئيسية']],
    ['id' => 'page.meta-info', 'path' => '/meta-info', 'section' => 'general', 'titleKey' => 'nav.meta-info', 'titleEn' => 'Meta Info', 'keywords' => ['meta', 'info']],
    ['id' => 'page.faqs', 'path' => '/faqs', 'section' => 'general', 'titleKey' => 'nav.frequently-asked-questions', 'titleEn' => 'FAQs', 'keywords' => ['faq', 'questions', 'أسئلة', 'الأسئلة الشائعة']],
    ['id' => 'page.minimum-stage-age', 'path' => '/minimum-stage-age', 'section' => 'general', 'titleKey' => 'nav.minimum-registration-age', 'titleEn' => 'Minimum Registration Age', 'keywords' => ['age', 'minimum age', 'registration age', 'سن القبول', 'العمر']],
    ['id' => 'page.careers', 'path' => '/careers', 'section' => 'general', 'titleKey' => 'nav.vacancies', 'titleEn' => 'Careers', 'keywords' => ['jobs', 'careers', 'hiring', 'وظائف', 'شغل', 'اشتغل']],
    ['id' => 'page.more-info', 'path' => '/more-info', 'section' => 'general', 'titleKey' => null, 'titleEn' => 'More Information', 'keywords' => ['info', 'more', 'معلومات']],
    ['id' => 'page.admission', 'path' => '/admission', 'section' => 'admission', 'titleKey' => 'nav.admission', 'titleEn' => 'Admission', 'keywords' => ['admission', 'apply', 'enroll', 'التقديم', 'القبول']],
    ['id' => 'page.admission-process', 'path' => '/admission/admission-process', 'section' => 'admission', 'titleKey' => 'nav.admission-process', 'titleEn' => 'Admission Process', 'keywords' => ['process', 'steps', 'خطوات التقديم']],
    ['id' => 'page.admission-requirements', 'path' => '/admission/admission-requirements', 'section' => 'admission', 'titleKey' => 'nav.admission-requirements', 'titleEn' => 'Admission Requirements', 'keywords' => ['requirements', 'documents', 'papers', 'متطلبات', 'أوراق', 'inside egypt', 'داخل مصر', 'outside egypt', 'abroad', 'خارج مصر', 'foreigners', 'expat', 'أجانب']],
    ['id' => 'page.admission-fees', 'path' => '/admission/admission-fees', 'section' => 'admission', 'titleKey' => 'nav.admission-fees', 'titleEn' => 'Tuition Fees', 'keywords' => ['fees', 'tuition', 'cost', 'price', 'مصروفات', 'رسوم']],
    ['id' => 'page.academics', 'path' => '/academics', 'section' => 'academics', 'titleKey' => 'nav.academics', 'titleEn' => 'Academics', 'keywords' => ['academics', 'curriculum', 'الأكاديميات']],
    ['id' => 'page.academics-kindergarten', 'path' => '/academics/kindergarten', 'section' => 'academics', 'titleKey' => 'nav.kindergarten', 'titleEn' => 'Kindergarten', 'keywords' => ['kindergarten', 'kg', 'روضة']],
    ['id' => 'page.academics-kindergarten-international', 'path' => '/academics/kindergarten-international', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'Kindergarten International', 'keywords' => ['kg international', 'روضة دولي']],
    ['id' => 'page.academics-kindergarten-national', 'path' => '/academics/kindergarten-national', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'Kindergarten National', 'keywords' => ['kg national', 'روضة ناشونال']],
    ['id' => 'page.academics-pre-kindergarten', 'path' => '/academics/pre-kindergarten', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'Pre-Kindergarten', 'keywords' => ['pre-k', 'playschool', 'بري كي', 'حضانة']],
    ['id' => 'page.academics-national', 'path' => '/academics/national', 'section' => 'academics', 'titleKey' => 'nav.national', 'titleEn' => 'National Department', 'keywords' => ['national', 'ناشونال', 'قومي']],
    ['id' => 'page.academics-british', 'path' => '/academics/british', 'section' => 'academics', 'titleKey' => 'nav.british', 'titleEn' => 'British Department', 'keywords' => ['british', 'igcse', 'cambridge', 'بريطاني']],
    ['id' => 'page.academics-american', 'path' => '/academics/american', 'section' => 'academics', 'titleKey' => 'nav.american', 'titleEn' => 'American Department', 'keywords' => ['american', 'cognia', 'أمريكي']],
    ['id' => 'page.academics-partners', 'path' => '/academics/partners', 'section' => 'academics', 'titleKey' => 'nav.partners', 'titleEn' => 'Partners', 'keywords' => ['partners', 'شركاء']],
    ['id' => 'page.academics-facilities', 'path' => '/academics/facilities', 'section' => 'academics', 'titleKey' => 'nav.facilities', 'titleEn' => 'Facilities', 'keywords' => ['facilities', 'campus', 'مرافق']],
    ['id' => 'page.academics-staff', 'path' => '/academics/staff', 'section' => 'academics', 'titleKey' => 'nav.staff', 'titleEn' => 'Staff', 'keywords' => ['staff', 'teachers', 'مدرسين', 'هيئة التدريس']],
    ['id' => 'page.academics-staff-national', 'path' => '/academics/staff/national-staff', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'National Staff', 'keywords' => ['national staff']],
    ['id' => 'page.academics-staff-british', 'path' => '/academics/staff/british-staff', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'British Staff', 'keywords' => ['british staff']],
    ['id' => 'page.academics-staff-american', 'path' => '/academics/staff/american-staff', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'American Staff', 'keywords' => ['american staff']],
    ['id' => 'page.academics-staff-kindergarten', 'path' => '/academics/staff/kindergarten-staff', 'section' => 'academics', 'titleKey' => null, 'titleEn' => 'Kindergarten Staff', 'keywords' => ['kg staff']],
    ['id' => 'page.students-life', 'path' => '/students-life', 'section' => 'students-life', 'titleKey' => 'nav.students-life', 'titleEn' => 'Students Life', 'keywords' => ['students life', 'حياة الطلاب']],
    ['id' => 'page.students-union', 'path' => '/students-life/students-union', 'section' => 'students-life', 'titleKey' => 'nav.students-union', 'titleEn' => 'Students Union', 'keywords' => ['union', 'اتحاد الطلاب']],
    ['id' => 'page.activities', 'path' => '/students-life/activities', 'section' => 'students-life', 'titleKey' => 'nav.activities', 'titleEn' => 'Activities', 'keywords' => ['activities', 'sports', 'أنشطة']],
    ['id' => 'page.library', 'path' => '/students-life/library', 'section' => 'students-life', 'titleKey' => 'nav.library', 'titleEn' => 'Library', 'keywords' => ['library', 'books', 'مكتبة']],
    ['id' => 'page.library-english-fairy-tales', 'path' => '/students-life/library/english-fairy-tales', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'English Fairy Tales', 'keywords' => ['fairy tales']],
    ['id' => 'page.library-english-drama', 'path' => '/students-life/library/english-drama', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'English Drama', 'keywords' => ['drama']],
    ['id' => 'page.library-english-levels', 'path' => '/students-life/library/english-levels', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'English Levels', 'keywords' => ['english levels']],
    ['id' => 'page.library-english-general', 'path' => '/students-life/library/english-general', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'English General', 'keywords' => ['english general']],
    ['id' => 'page.library-arabic-information', 'path' => '/students-life/library/arabic-information', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'Arabic Information', 'keywords' => ['arabic information']],
    ['id' => 'page.library-arabic-general', 'path' => '/students-life/library/arabic-general', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'Arabic General', 'keywords' => ['arabic general']],
    ['id' => 'page.library-arabic-religion', 'path' => '/students-life/library/arabic-religion', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'Arabic Religion', 'keywords' => ['arabic religion']],
    ['id' => 'page.library-arabic-stories', 'path' => '/students-life/library/arabic-stories', 'section' => 'students-life', 'titleKey' => null, 'titleEn' => 'Arabic Stories', 'keywords' => ['arabic stories']],
    ['id' => 'page.events', 'path' => '/events', 'section' => 'events', 'titleKey' => 'nav.events', 'titleEn' => 'Events', 'keywords' => ['events', 'فعاليات']],
    ['id' => 'page.national-calendar', 'path' => '/events/national-calendar', 'section' => 'events', 'titleKey' => 'nav.national-calendar', 'titleEn' => 'National School Calendar', 'keywords' => ['calendar', 'national calendar', 'تقويم']],
    ['id' => 'page.british-calendar', 'path' => '/events/british-calendar', 'section' => 'events', 'titleKey' => 'nav.british-calendar', 'titleEn' => 'British School Calendar', 'keywords' => ['calendar', 'british calendar']],
    ['id' => 'page.american-calendar', 'path' => '/events/american-calendar', 'section' => 'events', 'titleKey' => 'nav.american-calendar', 'titleEn' => 'American School Calendar', 'keywords' => ['calendar', 'american calendar']],
    ['id' => 'page.kg-calendars', 'path' => '/events/kg-calendars', 'section' => 'events', 'titleKey' => 'nav.kg-calendars', 'titleEn' => 'KG Calendars', 'keywords' => ['kg calendar']],
    ['id' => 'page.american-kg-calendar', 'path' => '/events/american-kg-calendar', 'section' => 'events', 'titleKey' => 'events-pages.kg-calendars-pages.american-kg-calendar.title', 'titleEn' => 'American KG Calendar', 'keywords' => ['american kg calendar']],
    ['id' => 'page.british-kg-calendar', 'path' => '/events/british-kg-calendar', 'section' => 'events', 'titleKey' => 'events-pages.kg-calendars-pages.british-kg-calendar.title', 'titleEn' => 'British KG Calendar', 'keywords' => ['british kg calendar']],
    ['id' => 'page.national-kg-calendar', 'path' => '/events/national-kg-calendar', 'section' => 'events', 'titleKey' => 'events-pages.kg-calendars-pages.national-kg-calendar.title', 'titleEn' => 'National KG Calendar', 'keywords' => ['national kg calendar']],
    ['id' => 'page.gallery', 'path' => '/gallery', 'section' => 'gallery', 'titleKey' => 'nav.gallery', 'titleEn' => 'Gallery', 'keywords' => ['gallery', 'معرض']],
    ['id' => 'page.gallery-photos', 'path' => '/gallery/photos', 'section' => 'gallery', 'titleKey' => 'nav.photos', 'titleEn' => 'Photos', 'keywords' => ['photos', 'pictures', 'صور']],
    ['id' => 'page.gallery-videos', 'path' => '/gallery/videos', 'section' => 'gallery', 'titleKey' => 'nav.videos', 'titleEn' => 'Videos', 'keywords' => ['videos', 'فيديو']],
    ['id' => 'page.gallery-360-tour', 'path' => '/gallery/360-tour', 'section' => 'gallery', 'titleKey' => 'nav.360-tour', 'titleEn' => '360 Tour', 'keywords' => ['360', 'tour', 'virtual tour', 'جولة']],
    ['id' => 'page.open-day-signup', 'path' => '/events/open-day-signup', 'section' => 'events', 'titleKey' => 'nav.open-day-signup', 'titleEn' => 'Open Day Signup', 'keywords' => ['events', 'فعاليات'] ]
];

const PUBLIC_DEPARTMENT_ROUTE_PATHS = [
    'national' => '/academics/national',
    'british'  => '/academics/british',
    'american' => '/academics/american',
    'early'    => '/academics/pre-kindergarten',
];
