name: Sync Vite React App Assets to cPanel via FTP
concurrency:
  group: production-assets-deployment
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    tags:
      - 'force-assets-sync*'


jobs:
  sync-global-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Sync assets to server home directory
        run: |
          lftp -c "
          set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
          mirror -R --verbose --only-newer assets/ assets/
          "
